Fix build error on case-sensitive systems
RepetierHost.csproj includes ColorSlider.designer.cs but the actual file
is called ColorSlider.Designer.cs with capital 'D'. That small
difference breaks the build on systems where the filesystem is
case-sensitive:

  error CS2001: Source file `view/utils/ColorSlider.designer.cs' could not be found

TIP: Mono can be told to ignore case-sensitivity like this:
  MONO_IOMAP=all xbuild ...
See http://mono-project.com/IOMap for more info.